#!/bin/bash
gcc envolvente_templados.c -lm -o envtempl.exe
./envtempl.exe emg1.Sound
./envtempl.exe emg2.Sound
./envtempl.exe emg3.Sound
./envtempl.exe emg4.Sound
./envtempl.exe emg5.Sound
./envtempl.exe emg6.Sound
./envtempl.exe emg7.Sound
gcc emgs_correlation_templates.c -lm -o correlacionsueno.exe
./correlacionsueno.exe ZF-MCV_2015-12-03_07_10_22_vs_5_band.Sound envolvente.emg3.Sound.dat
python3 figuras_p_correlaciones.py
