#!/bin/bash
set -e

gcc envolvente_templados.c -lm -o envtempl.exe
# Ejecutable templado numerador m
#con este formato de nombres, van a bien correr los scripts en python, sino hay que ponerse a cambiarlos.

for f in emg*Sound
do
    ./envtempl.exe $f 10 4
done




gcc emgs_correlation_templates.c -lm -o correlacionsueno.exe
# Ejecutable     archivo-a-procesar templado    numerador   m
for f in envolvente.emg*.dat
do
    ./correlacionsueno.exe ZF-MCV_2015-12-02_11_48_01_vs_18_band.Sound $f 10 4
done

#los argumentos del script son: -numerador -m -criterio -cantidadtemplados(tienen que estar ordenados del 1 al #detemplados que haya)
#ver que el archivo de señal completa en el script sea el que sea quiere comparar


python3 figuras_correlaciones_todos_emgs.py ZF-MCV_2015-12-02_11_48_01_vs_18_band.Sound ZF-MCV_2015-12-02_11_48_01_s_18.Sound 10 4 2 7

