#!/bin/bash
set -e

gcc envolvente_templados.c -lm -O2 -o envtempl.exe
# Ejecutable templado numerador m

for f in emg*.Sound  #paso por todos los archivos con ese nombre.
     do ./envtempl.exe $f
done

cp envtempl.exe FILTRADOS/envtempl.exe


cd FILTRADOS

for f in ZF*.Sound
    do ./envtempl.exe $f
done

cd ..

gcc emgs_correlation_templates-corr1arch.c -lm -O2 -o corr1arch.exe

ap=1
numfiles=$(ls FILTRADOS/envolvente.ZF*.dat | wc -l)

for f in FILTRADOS/envolvente.ZF*.Sound.dat
do 
    for s in envolvente.emg*.Sound.dat                 
    do  
        echo $ap de $numfiles archivos procesados       
        ./corr1arch.exe ${f##*/} $s # Ejecutable     archivo-a-procesar templado
    done
    
    ((ap+=1))
done

gcc emgs_correlation_templates-otraact.c -lm -O2 -o otraact.exe

ap=1

for f in FILTRADOS/envolvente.ZF*.Sound.dat
do 
             
        ./otraact.exe ${f##*/}

    echo $ap de $numfiles archivos procesados
    ((ap+=1))
done


